"""Consolida v7 e alias finais aplicando TRUNCADOS_KNOWN unicamente.
Remove duplicatas por chave canônica.
"""
import sys, re, shutil
sys.stdout.reconfigure(encoding='utf-8')
import pandas as pd
from pathlib import Path
from datetime import datetime

DIR = Path(r'C:\Users\medin\Desktop\backup_judx\flat_stj_20260424\exports')
V7 = DIR / 'composicao_stj_canonical_v7.csv'
ALIAS = DIR / 'stj_alias_ministros.csv'

TRUNCADOS_KNOWN = {
    'NANCY ANDRIGHI': 'FATIMA NANCY ANDRIGHI',
    'FATIMA NANCY ANDRIGHI': 'FATIMA NANCY ANDRIGHI',
    'OG FERNANDES': 'GERALDO OG NICEAS MARQUES FERNANDES',
    'GERALDO OG NICEAS MARQUES FERNANDES': 'GERALDO OG NICEAS MARQUES FERNANDES',
    'FRANCISCO FALCAO': 'FRANCISCO CANDIDO DE M FALCAO NETO',
    'FRANCISCO CANDIDO DE M FALCAO NETO': 'FRANCISCO CANDIDO DE M FALCAO NETO',
    'FRANCISCO CANDIDO DE MELO FALCAO NETO': 'FRANCISCO CANDIDO DE M FALCAO NETO',
    'HUMBERTO MARTINS': 'HUMBERTO EUSTAQUIO SOARES MARTINS',
    'HUMBERTO EUSTAQUIO SOARES MARTINS': 'HUMBERTO EUSTAQUIO SOARES MARTINS',
    'MARIA THEREZA DE ASSIS MOURA': 'MARIA THEREZA ROCHA DE ASSIS MOURA',
    'MARIA THEREZA ROCHA DE ASSIS MOURA': 'MARIA THEREZA ROCHA DE ASSIS MOURA',
    'MARIA THEREZA': 'MARIA THEREZA ROCHA DE ASSIS MOURA',
    'MARIA THEREZA DE ASSIS': 'MARIA THEREZA ROCHA DE ASSIS MOURA',
    'HERMAN BENJAMIN': 'ANTONIO HERMAN DE VASCONCELLOS E BENJAMIN',
    'ANTONIO HERMAN BENJAMIN': 'ANTONIO HERMAN DE VASCONCELLOS E BENJAMIN',
    'ANTONIO HERMAN DE V E BENJAMIN': 'ANTONIO HERMAN DE VASCONCELLOS E BENJAMIN',
    'ANTONIO HERMAN DE VASCONCELLOS E BENJAMIN': 'ANTONIO HERMAN DE VASCONCELLOS E BENJAMIN',
    'ANTONIO HERMAN DE VASCONCELOS E BENJAMIN': 'ANTONIO HERMAN DE VASCONCELLOS E BENJAMIN',
    'PAULO DE TARSO SANSEVERINO': 'PAULO DE TARSO VIEIRA SANSEVERINO',
    'PAULO DE TARSO VIEIRA SANSEVERINO': 'PAULO DE TARSO VIEIRA SANSEVERINO',
    'MOURA RIBEIRO': 'PAULO DIAS DE MOURA RIBEIRO',
    'PAULO MOURA RIBEIRO': 'PAULO DIAS DE MOURA RIBEIRO',
    'PAULO DIAS DE MOURA RIBEIRO': 'PAULO DIAS DE MOURA RIBEIRO',
    'MARIA ISABEL GALLOTTI': 'MARIA ISABEL DINIZ GALLOTTI RODRIGUES',
    'ISABEL GALLOTTI': 'MARIA ISABEL DINIZ GALLOTTI RODRIGUES',
    'ISABEL GALLOTI': 'MARIA ISABEL DINIZ GALLOTTI RODRIGUES',
    'MARIA ISABEL DINIZ GALLOTTI RODRIGUES': 'MARIA ISABEL DINIZ GALLOTTI RODRIGUES',
    'MARCO BUZZI': 'MARCO AURELIO GASTALDI BUZZI',
    'MARCOS BUZZI': 'MARCO AURELIO GASTALDI BUZZI',
    'MARCO AURELIO BUZZI': 'MARCO AURELIO GASTALDI BUZZI',
    'MARCO AURELIO GASTALDI BUZZI': 'MARCO AURELIO GASTALDI BUZZI',
    'MARCO AURELIO BELLIZZE': 'MARCO AURELIO BELLIZZE OLIVEIRA',
    'MARCO AURELIO BELLIZE': 'MARCO AURELIO BELLIZZE OLIVEIRA',
    'MARCO AURELIO BELLIZZE OLIVEIRA': 'MARCO AURELIO BELLIZZE OLIVEIRA',
    'MARCO AURELIO': 'MARCO AURELIO BELLIZZE OLIVEIRA',
    'RAUL ARAUJO': 'RAUL ARAUJO FILHO',
    'RAUL ARAUJO FILHO': 'RAUL ARAUJO FILHO',
    'ASSUSETE MAGALHAES': 'ASSUSETE DUMONT REIS MAGALHAES',
    'ASSUSETE DUMONT REIS MAGALHAES': 'ASSUSETE DUMONT REIS MAGALHAES',
    'ROGERIO SCHIETTI': 'ROGERIO SCHIETTI MACHADO CRUZ',
    'ROGERIO SCHIETTI CRUZ': 'ROGERIO SCHIETTI MACHADO CRUZ',
    'ROGERIO SCHIETTI MACHADO CRUZ': 'ROGERIO SCHIETTI MACHADO CRUZ',
    'SEBASTIAO REIS JUNIOR': 'SEBASTIAO ALVES DOS REIS JUNIOR',
    'SEBASTIAO REIS': 'SEBASTIAO ALVES DOS REIS JUNIOR',
    'SEBASTIAO ALVES DOS REIS JUNIOR': 'SEBASTIAO ALVES DOS REIS JUNIOR',
    'GURGEL DE FARIA': 'LUIZ ALBERTO GURGEL DE FARIA',
    'LUIZ ALBERTO GURGEL DE FARIA': 'LUIZ ALBERTO GURGEL DE FARIA',
    'SERGIO KUKINA': 'SERGIO LUIZ KUKINA',
    'SERGIO LUIZ KUKINA': 'SERGIO LUIZ KUKINA',
    'VILLAS BOAS CUEVA': 'RICARDO VILLAS BOAS CUEVA',
    'VILAS BOAS CUEVA': 'RICARDO VILLAS BOAS CUEVA',
    'RICARDO VILLAS BOAS CUEVA': 'RICARDO VILLAS BOAS CUEVA',
    'LAURITA VAZ': 'LAURITA HILARIO VAZ',
    'LAURITA HILARIO VAZ': 'LAURITA HILARIO VAZ',
    'JOAO OTAVIO DE NORONHA': 'JOAO OTAVIO DE NORONHA',
    'JOAO OTAVIO DE': 'JOAO OTAVIO DE NORONHA',
    'JOAO OTAVIO': 'JOAO OTAVIO DE NORONHA',
    'BENEDITO GONCALVES': 'BENEDITO GONCALVES',
    'TEODORO SILVA SANTOS': 'TEODORO SILVA SANTOS',
    'TEODORO SILVA': 'TEODORO SILVA SANTOS',
    'REGINA HELENA COSTA': 'REGINA HELENA COSTA',
    'REGINA HELENA': 'REGINA HELENA COSTA',
    'CARLOS PIRES BRANDAO': 'CARLOS AUGUSTO PIRES BRANDAO',
    'CARLOS AUGUSTO PIRES BRANDAO': 'CARLOS AUGUSTO PIRES BRANDAO',
    'MARLUCE CALDAS': 'MARIA MARLUCE CALDAS BEZERRA',
    'MARIA MARLUCE CALDAS': 'MARIA MARLUCE CALDAS BEZERRA',
    'MARIA MARLUCE CALDAS BEZERRA': 'MARIA MARLUCE CALDAS BEZERRA',
    'PAULO SERGIO DOMINGUES': 'PAULO SERGIO DOMINGUES',
    'AFRANIO VILELA': 'AFRANIO VILELA',
    'JOSE AFRANIO VILELA': 'AFRANIO VILELA',
    'DANIELA TEIXEIRA': 'DANIELA TEIXEIRA',
    'DANIELA RODRIGUES TEIXEIRA': 'DANIELA TEIXEIRA',
    'CARLOS CINI MARCHIONATTI': 'CARLOS CINI MARCHIONATTI',
    'LUIS CARLOS GAMBOGI': 'LUIS CARLOS BALBINO GAMBOGI',
    'LUIS CARLOS BALBINO GAMBOGI': 'LUIS CARLOS BALBINO GAMBOGI',
    'OTAVIO DE ALMEIDA TOLEDO': 'OTAVIO DE ALMEIDA TOLEDO',
    'OTAVIO DE ALMEIDA': 'OTAVIO DE ALMEIDA TOLEDO',
    'JESUINO RISSATO': 'JESUINO RISSATO',
    'JESUINO APARECIDO RISSATO': 'JESUINO RISSATO',
    'MESSOD AZULAY NETO': 'MESSOD AZULAY NETO',
    'MESSOD AZULAY': 'MESSOD AZULAY NETO',
    'JOEL ILAN PACIORNIK': 'JOEL ILAN PACIORNIK',
    'JOEL ILLAN PACIORNIK': 'JOEL ILAN PACIORNIK',
    'ANTONIO SALDANHA PALHEIRO': 'ANTONIO SALDANHA PALHEIRO',
    'ANTONIO SALDANHA': 'ANTONIO SALDANHA PALHEIRO',
    'REYNALDO SOARES DA FONSECA': 'REYNALDO SOARES DA FONSECA',
    'REYNALDO SOARES': 'REYNALDO SOARES DA FONSECA',
    'REYNALDO SOARES DA': 'REYNALDO SOARES DA FONSECA',
    'NEFI CORDEIRO': 'NEFI CORDEIRO',
    'FELIX FISCHER': 'FELIX FISCHER',
    'NAPOLEAO NUNES MAIA FILHO': 'NAPOLEAO NUNES MAIA FILHO',
    'NAPOLEAO NUNES MAIA': 'NAPOLEAO NUNES MAIA FILHO',
    'JORGE MUSSI': 'JORGE MUSSI',
    'LUIS FELIPE SALOMAO': 'LUIS FELIPE SALOMAO',
    'MAURO CAMPBELL MARQUES': 'MAURO CAMPBELL MARQUES',
    'MAURO LUIZ CAMPBELL MARQUES': 'MAURO CAMPBELL MARQUES',
    'ANTONIO CARLOS FERREIRA': 'ANTONIO CARLOS FERREIRA',
    'ANTONIO CARLOS': 'ANTONIO CARLOS FERREIRA',
    'RIBEIRO DANTAS': 'RIBEIRO DANTAS',
    'MARCELO NAVARRO RIBEIRO DANTAS': 'RIBEIRO DANTAS',
    'DIVA MALERBI': 'DIVA MALERBI',
    'DIVA PRESTES MARCONDES MALERBI': 'DIVA MALERBI',
    'DIVA PRESTES MARCONDES': 'DIVA MALERBI',
    'JOSE LAZARO ALFREDO GUIMARAES': 'LAZARO GUIMARAES',
    'LAZARO GUIMARAES': 'LAZARO GUIMARAES',
    'OLINDO HERCULANO DE': 'OLINDO HERCULANO DE MENEZES',
    'OLINDO HERCULANO DE MENEZES': 'OLINDO HERCULANO DE MENEZES',
}

def consolidar(k):
    if pd.isna(k) or not k: return k
    return TRUNCADOS_KNOWN.get(str(k).strip(), str(k).strip())

ts = datetime.now().strftime('%Y%m%d_%H%M%S')

# === V7 ===
print('=== V7 ===')
try:
    v7 = pd.read_csv(V7)
    shutil.copy2(V7, V7.with_suffix(f'.csv.bak_{ts}'))
    v7['ministro_key'] = v7['ministro_key'].apply(consolidar)
    print(f'  ministros antes: {v7["ministro_key"].nunique()}')
    v7.to_csv(V7, index=False, encoding='utf-8-sig')
    print(f'  ministros após consolidação: {v7["ministro_key"].nunique()}')
    print(f'  ✓ {V7.name} reescrito')
except Exception as e:
    print(f'  ✗ ERRO v7: {e}')

# === Alias ===
print('\n=== Alias ===')
try:
    a = pd.read_csv(ALIAS)
    shutil.copy2(ALIAS, ALIAS.with_suffix(f'.csv.bak_{ts}'))
    a['ministro_key'] = a['ministro_key'].apply(consolidar)
    print(f'  alias antes: {len(a)} linhas, {a["ministro_key"].nunique()} ministros')
    # Dedup: para cada ministro_key + nome_raw, manter primeira linha com maior n_docs
    a = a.sort_values('n_docs_flat', ascending=False).drop_duplicates(
        subset=['ministro_key','nome_raw'], keep='first'
    )
    print(f'  alias após dedup: {len(a)} linhas, {a["ministro_key"].nunique()} ministros')
    a.to_csv(ALIAS, index=False, encoding='utf-8-sig')
    print(f'  ✓ {ALIAS.name} reescrito')

    # Lista final de ministros
    print('\n  Ministros canônicos finais:')
    for k in sorted(a['ministro_key'].unique()):
        if pd.notna(k):
            print(f'    {k}')
except Exception as e:
    print(f'  ✗ ERRO alias: {e}')

print('\n✓ OK')
